# Generated by Django 2.2.5 on 2020-02-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, upload_to='diary_image'),
        ),
    ]
