# Generated by Django 2.2.5 on 2020-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='notes',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
