# Generated by Django 2.2.5 on 2020-01-27 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200127_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime.now, primary_key=True, serialize=False),
        ),
    ]
