# Generated by Django 2.2.5 on 2020-01-27 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200127_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='id',
            field=models.AutoField(auto_created=True, default=66, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
