# Generated by Django 2.2.5 on 2020-01-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200127_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='date',
        ),
    ]
