# Generated by Django 2.2.5 on 2020-01-27 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_diary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='id',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime.now, primary_key=True, serialize=False),
        ),
    ]
