# Generated by Django 2.2.5 on 2020-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20200127_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='feelgood',
            field=models.CharField(default='Fantastic', max_length=30),
        ),
        migrations.AddField(
            model_name='diary',
            name='fftime',
            field=models.CharField(default='Fantastic', max_length=30),
        ),
        migrations.AddField(
            model_name='diary',
            name='metime',
            field=models.CharField(default='Fantastic', max_length=30),
        ),
        migrations.AddField(
            model_name='diary',
            name='productivity',
            field=models.CharField(default='Fantastic', max_length=30),
        ),
    ]
