# Generated by Django 2.2.5 on 2020-02-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20200205_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='goal',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
