# Generated by Django 2.2.5 on 2020-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200206_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='feelgood',
            field=models.CharField(default='Fantastic', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fftime',
            field=models.CharField(default='Fantastic', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='goal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='metime',
            field=models.CharField(default='Fantastic', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='productivity',
            field=models.CharField(default='Fantastic', max_length=30, null=True),
        ),
    ]
